// Vendor self-hosted Noto woff2 subsets and generate fonts/fonts.css, so the
// site never calls a font CDN and Indic scripts render consistently on every
// device (PLAN.md M4). Re-run whenever FAMILIES changes.
//
// To add another Indian language: add its family/subset below and re-run.
// A single "Noto Sans" family already carries both Latin and Devanagari; other
// scripts live in their own Noto families (Noto Sans Tamil, Bengali, ...).
//
// Usage: node scripts/fetch-fonts.js

import fs from "node:fs";
import path from "node:path";

const FONTS_DIR = path.join(process.cwd(), "fonts");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0 Safari/537.36";

// family -> weights and the subsets worth keeping (skip scripts we don't use).
const FAMILIES = [
  {
    name: "Noto Sans",
    weights: [400, 700],
    subsets: ["latin", "latin-ext", "devanagari"],
  },
];

const slug = (s) => s.toLowerCase().replace(/\s+/g, "-");

async function fetchCss(family, weights) {
  const q =
    `family=${encodeURIComponent(family)}:wght@${weights.join(";")}` +
    `&display=swap`;
  const res = await fetch(`https://fonts.googleapis.com/css2?${q}`, {
    headers: { "User-Agent": UA },
  });
  if (!res.ok) throw new Error(`Google Fonts CSS ${res.status} for ${family}`);
  return res.text();
}

// Parse "/* subset */ @font-face { ... }" blocks.
function parseBlocks(css) {
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  const blocks = [];
  for (const [, subset, body] of css.matchAll(re)) {
    const pick = (key) => body.match(new RegExp(`${key}:\\s*([^;]+);`))?.[1].trim();
    const url = body.match(/url\(([^)]+)\)/)?.[1];
    blocks.push({
      subset,
      family: pick("font-family")?.replace(/['"]/g, ""),
      weight: pick("font-weight"),
      style: pick("font-style") || "normal",
      unicodeRange: pick("unicode-range"),
      url,
    });
  }
  return blocks;
}

async function download(url, dest) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`woff2 ${res.status} ${url}`);
  fs.writeFileSync(dest, Buffer.from(await res.arrayBuffer()));
}

async function main() {
  fs.mkdirSync(FONTS_DIR, { recursive: true });
  const faces = [];

  for (const family of FAMILIES) {
    const css = await fetchCss(family.name, family.weights);
    const blocks = parseBlocks(css).filter((b) =>
      family.subsets.includes(b.subset),
    );
    for (const b of blocks) {
      const file = `${slug(b.family)}-${b.weight}-${b.style}-${b.subset}.woff2`;
      await download(b.url, path.join(FONTS_DIR, file));
      faces.push({ ...b, file });
      console.log(`downloaded ${file}`);
    }
  }

  const css =
    "/* Generated by scripts/fetch-fonts.js — do not edit by hand. */\n\n" +
    faces
      .map((f) =>
        [
          "@font-face {",
          `  font-family: '${f.family}';`,
          `  font-style: ${f.style};`,
          `  font-weight: ${f.weight};`,
          "  font-display: swap;",
          `  src: url('/fonts/${f.file}') format('woff2');`,
          `  unicode-range: ${f.unicodeRange};`,
          "}",
        ].join("\n"),
      )
      .join("\n\n") + "\n";
  fs.writeFileSync(path.join(FONTS_DIR, "fonts.css"), css);
  console.log(`\nwrote fonts/fonts.css with ${faces.length} @font-face rules`);
}

main();
